'use client';
import { motion } from "framer-motion";
import { AlertTriangle, Shield, Info } from "lucide-react";

export default function AboutPage() {
  return (
    <div className="page-container py-16 px-4">
      <div className="max-w-4xl mx-auto">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mb-10">
          <h1 className="text-4xl font-bold text-surface-100 mb-4">About Sahayak AI</h1>
          <p className="text-surface-400 text-lg leading-relaxed">Sahayak AI is an AI-assisted guidance and routing platform designed to close the gap between eligible Scheduled Caste (SC) beneficiaries and the concessional financial schemes designed for them. Built for Smart India Hackathon.</p>
        </motion.div>

        {/* Main Disclaimer */}
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}
          className="glass-card p-8 mb-8 border-warning-500/30 bg-warning-500/5">
          <div className="flex items-start gap-4">
            <AlertTriangle className="w-8 h-8 text-warning-500 flex-shrink-0 mt-1" />
            <div>
              <h2 className="text-xl font-bold text-warning-400 mb-3">Platform Disclaimer</h2>
              <p className="text-warning-300 leading-relaxed">
                This platform provides AI-assisted information and preliminary eligibility guidance only. <strong>Final eligibility, loan sanction, interest rate, repayment terms, and application approval are determined by the competent authority and authorized Channel Partner under applicable scheme guidelines.</strong>
              </p>
              <p className="text-warning-300 leading-relaxed mt-3">
                Sahayak AI is not an official government portal and does not submit loan applications or make sanctioning decisions. All guidance provided is for informational and routing purposes only.
              </p>
            </div>
          </div>
        </motion.div>

        {/* Data Transparency */}
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.15 }} className="glass-card p-8 mb-8">
          <h2 className="text-2xl font-semibold text-surface-100 mb-5 flex items-center gap-2"><Shield className="w-6 h-6 text-primary-400" />Data Transparency</h2>
          <div className="space-y-4">
            <div className="flex items-start gap-3 p-4 bg-success-500/10 border border-success-500/20 rounded-xl">
              <span className="badge-verified text-sm">✓ Verified</span>
              <p className="text-surface-300 text-sm">Scheme data (interest rates, eligibility criteria, loan limits, document requirements) sourced from official NSFDC, MUDRA, and SIDBI documentation. Each record shows a Last Verified date.</p>
            </div>
            <div className="flex items-start gap-3 p-4 bg-info-500/10 border border-info-500/20 rounded-xl">
              <span className="badge-ai text-sm">🤖 AI-Generated</span>
              <p className="text-surface-300 text-sm">Match explanations, scheme summaries, and assistant responses generated by Gemini AI, grounded in the verified scheme database. AI never fabricates official figures.</p>
            </div>
            <div className="flex items-start gap-3 p-4 bg-warning-500/10 border border-warning-500/20 rounded-xl">
              <span className="badge-demo text-sm">⚠️ Demo Data</span>
              <p className="text-surface-300 text-sm">Channel Partner routing status (Available / Limited / Restricted) is prototype data not backed by a live official feed. This will be replaced with verified live data when official integration is established.</p>
            </div>
          </div>
        </motion.div>

        {/* Mission & Non-Goals */}
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }} className="glass-card p-8 mb-8">
          <h2 className="text-2xl font-semibold text-surface-100 mb-5">Mission</h2>
          <p className="text-surface-300 leading-relaxed mb-4">A citizen with no prior knowledge of government financial schemes should be able to describe their situation in plain language and, within minutes, know: which scheme fits me, how much I could get and what I'd repay monthly, and exactly which authorized partner near me can actually process it right now.</p>
          <h3 className="text-lg font-semibold text-surface-200 mb-3 mt-6">What this platform does NOT do:</h3>
          <ul className="space-y-2 text-surface-400 text-sm">
            {["Submit loan applications on your behalf", "Make eligibility or sanctioning decisions", "Store uploaded documents (not implemented in this version)", "Replace the official Channel Partner or competent authority", "Guarantee any loan amount, rate, or approval outcome"].map(item => (
              <li key={item} className="flex items-center gap-2"><span className="w-1.5 h-1.5 rounded-full bg-danger-500/60 flex-shrink-0" />{item}</li>
            ))}
          </ul>
        </motion.div>

        {/* Privacy */}
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.25 }} className="glass-card p-8">
          <h2 className="text-2xl font-semibold text-surface-100 mb-5 flex items-center gap-2"><Info className="w-6 h-6 text-info-400" />Privacy Policy</h2>
          <div className="space-y-4 text-surface-300 text-sm leading-relaxed">
            <p><strong>Data collected:</strong> Only the minimum required for scheme matching — name (optional), age, state, district, social category, income range, business purpose, and loan requirement. Location data is only used if you explicitly click "Use My Location" and is never stored server-side.</p>
            <p><strong>Data storage:</strong> Profile data is stored in Firebase Firestore (Google Cloud) and associated with your authenticated account. It is not shared with third parties.</p>
            <p><strong>Data deletion:</strong> You may request account and data deletion by contacting us. There is no data retention period beyond your active account.</p>
            <p><strong>Cookies:</strong> We use only essential session cookies for authentication. No third-party tracking cookies.</p>
            <p><strong>Built for:</strong> Smart India Hackathon — implementation-ready prototype. Official deployment subject to additional security, privacy, and accessibility audits.</p>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
