export type SchemeCategory = "micro_finance" | "small_business_loan" | "term_loan" | "micro" | "small" | "medium";
export type SchemePurpose = "business_start" | "business_expansion" | "machinery" | "working_capital" | "skill_development" | "agriculture";
export type PartnerType = "SCA" | "PSB" | "RRB" | "NBFC-MFI" | "NBFC" | "Co-operative Bank";
export type SchemeStatus = "active" | "inactive" | "expired" | "discontinued";

export interface Scheme {
  id: string;
  scheme_id?: string;
  name: string;
  shortName: string;
  shortCode?: string;
  short_code?: string;
  description: string;
  purpose: SchemePurpose[];
  category: SchemeCategory[];
  ministry?: string;
  department?: string;
  implementingBody?: string;
  implementing_body?: string;
  governmentLevel?: "central" | "state";
  government_level?: "central" | "state";
  minAge: number;
  maxAge: number;
  incomeLimitLakh: number;
  income_ceiling?: number;
  incomeCeilingEffectiveDate?: string;
  income_ceiling_effective_date?: string;
  minLoanLakh: number;
  maxLoanLakh: number;
  max_loan_amount?: number;
  loan_limit?: string;
  projectCostMinLakh?: number;
  project_cost_min?: number;
  projectCostMaxLakh?: number;
  project_cost_max?: number;
  financingPercent: number;
  financing_percentage?: number;
  interestRatePercent: number;
  interest_rate_beneficiary_pct?: number;
  interestRateCaPercent?: number;
  interest_rate_ca_pct?: number;
  genderBasedRate?: boolean;
  gender_based_rate?: boolean;
  interestRateMen?: number;
  interest_rate_beneficiary_pct_men?: number;
  interestRateWomen?: number;
  interest_rate_beneficiary_pct_women?: number;
  interestRateCaMen?: number;
  interest_rate_ca_pct_men?: number;
  interestRateCaWomen?: number;
  interest_rate_ca_pct_women?: number;
  moratoriumMonthsMin: number;
  moratoriumMonthsMax: number;
  moratorium_period?: string;
  moratoriumPeriodDesc?: string;
  repaymentYears: number;
  repayment_period?: string;
  repaymentPeriodDesc?: string;
  eligibleCategories: string[];
  genderCriteria: "any" | "women_only" | "other";
  gender_criteria?: "any" | "women_only" | "other";
  collateralRequired?: boolean;
  collateral_required?: boolean;
  channelRoute?: string;
  channel_route?: string;
  requiredDocuments: string[];
  businessTypes: string[];
  officialUrl: string;
  official_url?: string;
  applicationPortal?: string;
  application_portal?: string;
  nodal: string;
  lastVerified: string;
  last_verified?: string;
  source: string;
  sourceUrl?: string;
  source_url?: string;
  partnerTypes: PartnerType[];
  states: string[] | "all";
  tags: string[];
  color: string;
  icon: string;
  status: SchemeStatus;
  notes?: string;
}

export const SCHEMES: Scheme[] = [
  {
    id: "nsfdc-msy",
    scheme_id: "nsfdc-msy",
    name: "Mahila Samriddhi Yojana (MSY)",
    shortName: "Mahila Samriddhi",
    shortCode: "MSY",
    short_code: "MSY",
    description: "Micro-financing scheme exclusively for Scheduled Caste (SC) women entrepreneurs. Provides concessional loans for micro and small income-generating activities with priority to rural and marginalized women.",
    purpose: ["business_start", "working_capital", "skill_development"],
    category: ["micro_finance", "micro"],
    ministry: "Ministry of Social Justice & Empowerment",
    implementingBody: "NSFDC",
    implementing_body: "NSFDC",
    governmentLevel: "central",
    government_level: "central",
    minAge: 18,
    maxAge: 60,
    incomeLimitLakh: 5.0,
    income_ceiling: 500000,
    incomeCeilingEffectiveDate: "2026-01-07",
    income_ceiling_effective_date: "2026-01-07",
    minLoanLakh: 0.1,
    maxLoanLakh: 1.25,
    max_loan_amount: 125000,
    projectCostMaxLakh: 1.40,
    project_cost_max: 140000,
    financingPercent: 90,
    financing_percentage: 90,
    interestRatePercent: 6.0,
    interest_rate_beneficiary_pct: 6.0,
    interestRateCaPercent: 2.0,
    interest_rate_ca_pct: 2.0,
    moratoriumMonthsMin: 3,
    moratoriumMonthsMax: 3,
    moratorium_period: "3 months",
    moratoriumPeriodDesc: "3 months",
    repaymentYears: 3,
    repayment_period: "Within 3 years",
    repaymentPeriodDesc: "Within 3 years",
    eligibleCategories: ["SC"],
    genderCriteria: "women_only",
    gender_criteria: "women_only",
    collateralRequired: false,
    collateral_required: false,
    channelRoute: "SCAs / PSBs / RRBs",
    channel_route: "SCAs / PSBs / RRBs",
    requiredDocuments: [
      "Caste Certificate (SC)",
      "Income Certificate (Family income within ₹5.0 Lakh)",
      "Aadhaar Card",
      "Passport-size photographs",
      "Proof of proposed income-generating activity / trade",
      "Bank account details (Passbook copy / cancelled cheque)",
    ],
    businessTypes: ["tailoring", "handicraft", "food processing", "vegetable vending", "retail trade", "beauty parlour", "dairy"],
    officialUrl: "https://nsfdc.nic.in",
    official_url: "https://nsfdc.nic.in",
    applicationPortal: "https://pmsuraj.dosje.gov.in",
    application_portal: "https://pmsuraj.dosje.gov.in",
    nodal: "National Scheduled Castes Finance and Development Corporation (NSFDC)",
    lastVerified: "2026-09-08",
    last_verified: "2026-09-08",
    source: "socialjustice.gov.in Annexure-I(a), NSFDC scheme table",
    sourceUrl: "https://socialjustice.gov.in/writereaddata/UploadFile/49061739958522.pdf",
    source_url: "https://socialjustice.gov.in/writereaddata/UploadFile/49061739958522.pdf",
    partnerTypes: ["SCA", "PSB", "RRB"],
    states: "all",
    tags: ["women only", "micro-finance", "SC", "MSY", "low interest", "concessional"],
    color: "from-pink-500 to-rose-600",
    icon: "👩‍💼",
    status: "active",
    notes: "Exclusively for SC women. Channelizing Agency interest rate is 2.0%, beneficiary pays 6.0% p.a."
  },
  {
    id: "nsfdc-mcf",
    scheme_id: "nsfdc-mcf",
    name: "Micro Credit Finance (MCF)",
    shortName: "Micro Credit Finance",
    shortCode: "MCF",
    short_code: "MCF",
    description: "Financial assistance for small and petty trade and sundry income-generating activities such as betel leaf shop, bakery, cycle repair, goatery, candle making, and tea stall for SC entrepreneurs.",
    purpose: ["business_start", "working_capital", "machinery"],
    category: ["micro_finance", "micro"],
    ministry: "Ministry of Social Justice & Empowerment",
    implementingBody: "NSFDC",
    implementing_body: "NSFDC",
    governmentLevel: "central",
    government_level: "central",
    minAge: 18,
    maxAge: 60,
    incomeLimitLakh: 5.0,
    income_ceiling: 500000,
    incomeCeilingEffectiveDate: "2026-01-07",
    income_ceiling_effective_date: "2026-01-07",
    minLoanLakh: 0.1,
    maxLoanLakh: 1.25,
    max_loan_amount: 125000,
    projectCostMaxLakh: 1.40,
    project_cost_max: 140000,
    financingPercent: 90,
    financing_percentage: 90,
    interestRatePercent: 6.5,
    interest_rate_beneficiary_pct: 6.5,
    interestRateCaPercent: 2.5,
    interest_rate_ca_pct: 2.5,
    moratoriumMonthsMin: 3,
    moratoriumMonthsMax: 3,
    moratorium_period: "3 months",
    moratoriumPeriodDesc: "3 months",
    repaymentYears: 3,
    repayment_period: "Within 3 years",
    repaymentPeriodDesc: "Within 3 years",
    eligibleCategories: ["SC"],
    genderCriteria: "any",
    gender_criteria: "any",
    collateralRequired: false,
    collateral_required: false,
    channelRoute: "SCAs / PSBs / RRBs",
    channel_route: "SCAs / PSBs / RRBs",
    requiredDocuments: [
      "Caste Certificate (SC)",
      "Income Certificate (Family income within ₹5.0 Lakh)",
      "Aadhaar Card",
      "Passport-size photographs",
      "Brief description of petty trade / micro-business",
      "Bank account details",
    ],
    businessTypes: ["petty trade", "bakery", "cycle repair", "candle making", "goatery", "tea stall", "vegetable vending", "tailoring"],
    officialUrl: "https://nsfdc.nic.in",
    official_url: "https://nsfdc.nic.in",
    applicationPortal: "https://pmsuraj.dosje.gov.in",
    application_portal: "https://pmsuraj.dosje.gov.in",
    nodal: "NSFDC — Micro Credit Finance",
    lastVerified: "2026-09-08",
    last_verified: "2026-09-08",
    source: "socialjustice.gov.in Annexure-I(a); cross-checked against nsfdc.nic.in scheme page",
    sourceUrl: "https://socialjustice.gov.in/writereaddata/UploadFile/49061739958522.pdf",
    source_url: "https://socialjustice.gov.in/writereaddata/UploadFile/49061739958522.pdf",
    partnerTypes: ["SCA", "PSB", "RRB"],
    states: "all",
    tags: ["micro credit", "petty trade", "SC", "MCF", "working capital"],
    color: "from-amber-500 to-orange-600",
    icon: "🏪",
    status: "active",
  },
  {
    id: "nsfdc-suvidha",
    scheme_id: "nsfdc-suvidha",
    name: "Suvidha Loan Scheme",
    shortName: "Suvidha Loan",
    shortCode: "SUVIDHA",
    short_code: "SUVIDHA",
    description: "Self-employment loans for small business activities tailored to beneficiary needs. Replaced the former Term Loan scheme for projects up to ₹10 Lakh, absorbing Stand-Up India (NSFDC component), Green Business, Swachhta Udyami, and Mahila Adhikarita.",
    purpose: ["business_start", "business_expansion", "machinery", "working_capital"],
    category: ["small_business_loan", "small"],
    ministry: "Ministry of Social Justice & Empowerment",
    implementingBody: "NSFDC",
    implementing_body: "NSFDC",
    governmentLevel: "central",
    government_level: "central",
    minAge: 18,
    maxAge: 60,
    incomeLimitLakh: 5.0,
    income_ceiling: 500000,
    incomeCeilingEffectiveDate: "2026-01-07",
    income_ceiling_effective_date: "2026-01-07",
    minLoanLakh: 0.5,
    maxLoanLakh: 9.0,
    max_loan_amount: 900000,
    projectCostMaxLakh: 10.0,
    project_cost_max: 1000000,
    financingPercent: 90,
    financing_percentage: 90,
    interestRatePercent: 8.0,
    interest_rate_beneficiary_pct: 8.0,
    interestRateCaPercent: 4.0,
    interest_rate_ca_pct: 4.0,
    moratoriumMonthsMin: 6,
    moratoriumMonthsMax: 12,
    moratorium_period: "6 months (12 months for plantation/construction activities)",
    moratoriumPeriodDesc: "6 months (12 months for plantation/construction activities)",
    repaymentYears: 5,
    repayment_period: "Within 5 years",
    repaymentPeriodDesc: "Within 5 years",
    eligibleCategories: ["SC"],
    genderCriteria: "any",
    gender_criteria: "any",
    collateralRequired: false,
    collateral_required: false,
    channelRoute: "SCAs / PSBs / RRBs",
    channel_route: "SCAs / PSBs / RRBs",
    requiredDocuments: [
      "Caste Certificate (SC)",
      "Income Certificate (Family income up to ₹5.0 Lakh)",
      "Aadhaar Card / Voter ID",
      "Passport-size photographs",
      "Project Report / Business Quotation",
      "Bank statement (last 6 months)",
      "Rent agreement or shop ownership proof (if applicable)",
    ],
    businessTypes: ["manufacturing", "tailoring unit", "trade", "service", "workshop", "food processing", "green business", "transport"],
    officialUrl: "https://nsfdc.nic.in/en/suvidha-loan",
    official_url: "https://nsfdc.nic.in/en/suvidha-loan",
    applicationPortal: "https://pmsuraj.dosje.gov.in",
    application_portal: "https://pmsuraj.dosje.gov.in",
    nodal: "NSFDC — Suvidha Loan Scheme",
    lastVerified: "2026-09-08",
    last_verified: "2026-09-08",
    source: "NSFDC official scheme page + socialjustice.gov.in Annexure-I(a)",
    sourceUrl: "https://nsfdc.nic.in/en/suvidha-loan",
    source_url: "https://nsfdc.nic.in/en/suvidha-loan",
    partnerTypes: ["SCA", "PSB", "RRB"],
    states: "all",
    tags: ["suvidha", "small business", "self-employment", "SC", "term loan replacement"],
    color: "from-indigo-500 to-purple-600",
    icon: "🏭",
    status: "active",
    notes: "Replaced Term Loan (for projects up to Rs.10 lakh) effective 01.10.2023. Absorbed Green Business Scheme, Stand-Up India (NSFDC component), Swachhta Udyami Yojana, and Mahila Adhikarita Yojana."
  },
  {
    id: "nsfdc-utkarsh",
    scheme_id: "nsfdc-utkarsh",
    name: "Utkarsh Loan Scheme",
    shortName: "Utkarsh Loan",
    shortCode: "UTKARSH",
    short_code: "UTKARSH",
    description: "Self-employment loans for larger business/manufacturing projects (replaced Term Loan for projects above Rs. 10 lakh, effective 01.10.2023)",
    purpose: ["business_start", "business_expansion", "machinery"],
    category: ["term_loan", "medium"],
    ministry: "Ministry of Social Justice & Empowerment",
    implementingBody: "NSFDC",
    implementing_body: "NSFDC",
    governmentLevel: "central",
    government_level: "central",
    minAge: 18,
    maxAge: 60,
    incomeLimitLakh: 5.0,
    income_ceiling: 500000,
    incomeCeilingEffectiveDate: "2026-01-07",
    income_ceiling_effective_date: "2026-01-07",
    minLoanLakh: 9.0,
    maxLoanLakh: 45.0,
    max_loan_amount: 4500000,
    projectCostMinLakh: 10.0,
    project_cost_min: 1000000,
    projectCostMaxLakh: 50.0,
    project_cost_max: 5000000,
    financingPercent: 90,
    financing_percentage: 90,
    interestRatePercent: 9.0,
    interest_rate_beneficiary_pct: 9.0,
    interestRateCaPercent: 5.0,
    interest_rate_ca_pct: 5.0,
    moratoriumMonthsMin: 6,
    moratoriumMonthsMax: 12,
    moratorium_period: "6 months (12 months for plantation/construction activities)",
    moratoriumPeriodDesc: "6 months (12 months for plantation/construction activities)",
    repaymentYears: 7,
    repayment_period: "Within 7 years",
    repaymentPeriodDesc: "Within 7 years",
    eligibleCategories: ["SC"],
    genderCriteria: "any",
    gender_criteria: "any",
    collateralRequired: true,
    channelRoute: "SCAs / PSBs / RRBs",
    channel_route: "SCAs / PSBs / RRBs",
    requiredDocuments: [
      "Caste Certificate (SC)",
      "Income Certificate (Family income up to ₹5.0 Lakh)",
      "Aadhaar & PAN Card",
      "Detailed Project Report (DPR) with cash flow projections",
      "Udyam Registration / GST Registration",
      "Audited financial statements / IT returns (if existing unit)",
      "Quotations for plant, machinery & equipment",
      "Collateral security documents",
    ],
    businessTypes: ["manufacturing", "engineering", "agro-processing", "commercial enterprise", "logistics"],
    officialUrl: "https://nsfdc.nic.in",
    official_url: "https://nsfdc.nic.in",
    applicationPortal: "https://pmsuraj.dosje.gov.in",
    application_portal: "https://pmsuraj.dosje.gov.in",
    nodal: "NSFDC — Utkarsh Loan Scheme",
    lastVerified: "2026-09-08",
    last_verified: "2026-09-08",
    source: "socialjustice.gov.in Annexure-I(a); cross-checked against NSFDC Term Loan replacement notice",
    sourceUrl: "https://socialjustice.gov.in/writereaddata/UploadFile/49061739958522.pdf",
    source_url: "https://socialjustice.gov.in/writereaddata/UploadFile/49061739958522.pdf",
    partnerTypes: ["SCA", "PSB", "RRB"],
    states: "all",
    tags: ["utkarsh", "large loan", "machinery", "manufacturing", "SC"],
    color: "from-violet-600 to-blue-700",
    icon: "🏢",
    status: "active",
    notes: "Replaced Term Loan (for projects above Rs.10 lakh, up to Rs.50 lakh) effective 01.10.2023."
  },
  {
    id: "nsfdc-amy",
    scheme_id: "nsfdc-amy",
    name: "Aajeevika Microfinance Yojana (AMY)",
    shortName: "Aajeevika Microfinance",
    shortCode: "AMY",
    short_code: "AMY",
    description: "Prompt, need-based micro finance for small/micro business activities via NBFC-MFIs",
    purpose: ["business_start", "working_capital"],
    category: ["micro_finance", "micro"],
    ministry: "Ministry of Social Justice & Empowerment",
    implementingBody: "NSFDC",
    implementing_body: "NSFDC",
    governmentLevel: "central",
    government_level: "central",
    minAge: 18,
    maxAge: 60,
    incomeLimitLakh: 5.0,
    income_ceiling: 500000,
    incomeCeilingEffectiveDate: "2026-01-07",
    income_ceiling_effective_date: "2026-01-07",
    minLoanLakh: 0.1,
    maxLoanLakh: 1.25,
    max_loan_amount: 125000,
    projectCostMaxLakh: 1.40,
    project_cost_max: 140000,
    financingPercent: 90,
    financing_percentage: 90,
    interestRatePercent: 15.0,
    interest_rate_beneficiary_pct: 15.0,
    interestRateCaPercent: 5.0,
    interest_rate_ca_pct: 5.0,
    moratoriumMonthsMin: 3,
    moratoriumMonthsMax: 3,
    moratorium_period: "3 months",
    moratoriumPeriodDesc: "3 months",
    repaymentYears: 3,
    repayment_period: "Within 3 years",
    repaymentPeriodDesc: "Within 3 years",
    eligibleCategories: ["SC"],
    genderCriteria: "any",
    gender_criteria: "any",
    collateralRequired: false,
    collateral_required: false,
    channelRoute: "NBFC-MFIs",
    channel_route: "NBFC-MFIs",
    requiredDocuments: [
      "Caste Certificate (SC)",
      "Income Certificate (within ₹5.0 Lakh)",
      "Aadhaar Card",
      "Self-help Group / Joint Liability Group membership proof (if applicable)",
      "Bank account details",
    ],
    businessTypes: ["handicraft", "micro trade", "livestock", "vegetables", "service"],
    officialUrl: "https://nsfdc.nic.in",
    official_url: "https://nsfdc.nic.in",
    applicationPortal: "https://pmsuraj.dosje.gov.in",
    application_portal: "https://pmsuraj.dosje.gov.in",
    nodal: "NSFDC — Aajeevika Microfinance",
    lastVerified: "2026-09-08",
    last_verified: "2026-09-08",
    source: "socialjustice.gov.in Annexure-I(a)",
    sourceUrl: "https://socialjustice.gov.in/writereaddata/UploadFile/49061739958522.pdf",
    source_url: "https://socialjustice.gov.in/writereaddata/UploadFile/49061739958522.pdf",
    partnerTypes: ["NBFC-MFI"],
    states: "all",
    tags: ["microfinance", "NBFC-MFI", "doorstep delivery", "SC"],
    color: "from-emerald-500 to-teal-700",
    icon: "🤝",
    status: "active",
    notes: "Higher beneficiary interest rate (15%) reflects NBFC-MFI cost of funds vs. bank/SCA-routed schemes."
  },
  {
    id: "nsfdc-uny",
    scheme_id: "nsfdc-uny",
    name: "Udyam Nidhi Yojana (UNY)",
    shortName: "Udyam Nidhi",
    shortCode: "UNY",
    short_code: "UNY",
    description: "Small business financing routed through Co-operative Societies / Co-operative Banks",
    purpose: ["business_start", "working_capital", "machinery"],
    category: ["small_business_loan", "small"],
    ministry: "Ministry of Social Justice & Empowerment",
    implementingBody: "NSFDC",
    implementing_body: "NSFDC",
    governmentLevel: "central",
    government_level: "central",
    minAge: 18,
    maxAge: 60,
    incomeLimitLakh: 5.0,
    income_ceiling: 500000,
    incomeCeilingEffectiveDate: "2026-01-07",
    income_ceiling_effective_date: "2026-01-07",
    minLoanLakh: 0.5,
    maxLoanLakh: 4.5,
    max_loan_amount: 450000,
    projectCostMaxLakh: 5.0,
    project_cost_max: 500000,
    financingPercent: 90,
    financing_percentage: 90,
    interestRatePercent: 13.0,
    interest_rate_beneficiary_pct: 13.0,
    interestRateCaPercent: 5.0,
    interest_rate_ca_pct: 5.0,
    moratoriumMonthsMin: 3,
    moratoriumMonthsMax: 3,
    moratorium_period: "3 months",
    moratoriumPeriodDesc: "3 months",
    repaymentYears: 5,
    repayment_period: "Within 5 years",
    repaymentPeriodDesc: "Within 5 years",
    eligibleCategories: ["SC"],
    genderCriteria: "any",
    gender_criteria: "any",
    collateralRequired: false,
    collateral_required: false,
    channelRoute: "Co-operative Societies / Co-operative Banks",
    channel_route: "Co-operative Societies / Co-operative Banks",
    requiredDocuments: [
      "Caste Certificate (SC)",
      "Income Certificate (within ₹5.0 Lakh)",
      "Aadhaar Card",
      "Membership proof in registered Co-operative Society/Bank",
      "Business proposal quotation",
    ],
    businessTypes: ["cooperative business", "dairy", "handloom", "agro retail", "small manufacturing"],
    officialUrl: "https://nsfdc.nic.in",
    official_url: "https://nsfdc.nic.in",
    applicationPortal: "https://pmsuraj.dosje.gov.in",
    application_portal: "https://pmsuraj.dosje.gov.in",
    nodal: "NSFDC — Udyam Nidhi",
    lastVerified: "2026-09-08",
    last_verified: "2026-09-08",
    source: "socialjustice.gov.in Annexure-I(a)",
    sourceUrl: "https://socialjustice.gov.in/writereaddata/UploadFile/49061739958522.pdf",
    source_url: "https://socialjustice.gov.in/writereaddata/UploadFile/49061739958522.pdf",
    partnerTypes: ["Co-operative Bank", "SCA"],
    states: "all",
    tags: ["cooperative", "udyam nidhi", "grassroots", "SC"],
    color: "from-teal-500 to-cyan-700",
    icon: "🌾",
    status: "active",
  },
  {
    id: "pm-svanidhi",
    name: "PM SVANidhi Scheme",
    shortName: "PM SVANidhi",
    shortCode: "PM-SVANIDHI",
    description: "Micro-credit facility for urban and peri-urban street vendors to resume livelihoods. Collateral-free working capital loan starting at ₹10,000, upgrading to ₹20,000 and ₹50,000 upon timely digital repayments with 7% interest subsidy.",
    purpose: ["working_capital", "business_start"],
    category: ["micro_finance", "micro"],
    ministry: "Ministry of Housing and Urban Affairs",
    governmentLevel: "central",
    minAge: 18,
    maxAge: 65,
    incomeLimitLakh: 5.0,
    minLoanLakh: 0.1,
    maxLoanLakh: 0.5,
    financingPercent: 100,
    interestRatePercent: 7.0,
    moratoriumMonthsMin: 0,
    moratoriumMonthsMax: 3,
    repaymentYears: 1,
    repaymentPeriodDesc: "1 year for 1st tranche, 18 months for 2nd tranche",
    eligibleCategories: ["SC", "ST", "OBC", "General"],
    genderCriteria: "any",
    collateralRequired: false,
    channelRoute: "PSBs / RRBs / NBFC-MFIs",
    requiredDocuments: [
      "Aadhaar Card linked to active mobile number",
      "Vending Certificate / Urban Local Body Letter of Recommendation",
      "Bank account details (UPI linked preferred)",
      "Passport-size photograph",
    ],
    businessTypes: ["street vending", "micro trade", "food vending", "fruit/vegetables"],
    officialUrl: "https://pmsvanidhi.mohua.gov.in",
    applicationPortal: "https://pmsvanidhi.mohua.gov.in",
    nodal: "Ministry of Housing and Urban Affairs",
    lastVerified: "2026-09-08",
    source: "pmsvanidhi.mohua.gov.in official portal",
    sourceUrl: "https://pmsvanidhi.mohua.gov.in",
    partnerTypes: ["PSB", "RRB", "NBFC-MFI"],
    states: "all",
    tags: ["street vendor", "micro-credit", "working capital", "collateral-free", "digital subsidy"],
    color: "from-orange-500 to-yellow-600",
    icon: "🛒",
    status: "active",
  },
  {
    id: "mudra-shishu",
    name: "MUDRA Loan — Shishu",
    shortName: "MUDRA Shishu",
    shortCode: "MUDRA-SHISHU",
    description: "Collateral-free micro-loans up to ₹50,000 for establishing a new micro-enterprise or stabilizing a nascent business. Ideal for first-time entrepreneurs.",
    purpose: ["business_start", "working_capital"],
    category: ["micro_finance", "micro"],
    ministry: "Ministry of Finance",
    implementingBody: "MUDRA / Banks",
    governmentLevel: "central",
    minAge: 18,
    maxAge: 65,
    incomeLimitLakh: 10.0,
    minLoanLakh: 0.05,
    maxLoanLakh: 0.5,
    financingPercent: 100,
    interestRatePercent: 9.5,
    moratoriumMonthsMin: 0,
    moratoriumMonthsMax: 6,
    repaymentYears: 5,
    eligibleCategories: ["SC", "ST", "OBC", "General"],
    genderCriteria: "any",
    collateralRequired: false,
    channelRoute: "PSBs / RRBs / NBFC-MFIs",
    requiredDocuments: [
      "Aadhaar Card / Voter ID",
      "PAN Card",
      "Business outline / activity quotation",
      "Bank account statement (last 6 months)",
      "Passport-size photographs",
    ],
    businessTypes: ["micro-enterprise", "trade", "service", "manufacturing", "tailoring"],
    officialUrl: "https://mudra.org.in",
    applicationPortal: "https://udyamimitra.in",
    nodal: "Micro Units Development & Refinance Agency (MUDRA)",
    lastVerified: "2026-09-08",
    source: "mudra.org.in official portal",
    partnerTypes: ["PSB", "RRB", "NBFC-MFI"],
    states: "all",
    tags: ["MUDRA", "micro-loan", "collateral-free", "startup"],
    color: "from-green-500 to-emerald-600",
    icon: "🌱",
    status: "active",
  },
  {
    id: "mudra-kishore",
    name: "MUDRA Loan — Kishore",
    shortName: "MUDRA Kishore",
    shortCode: "MUDRA-KISHORE",
    description: "Loans from ₹50,001 to ₹5 Lakh for established micro-enterprises looking to scale operations, buy machinery, or expand stock inventory.",
    purpose: ["business_expansion", "working_capital", "machinery"],
    category: ["small_business_loan", "small"],
    ministry: "Ministry of Finance",
    implementingBody: "MUDRA / Banks",
    governmentLevel: "central",
    minAge: 18,
    maxAge: 65,
    incomeLimitLakh: 10.0,
    minLoanLakh: 0.5,
    maxLoanLakh: 5.0,
    financingPercent: 90,
    interestRatePercent: 10.5,
    moratoriumMonthsMin: 3,
    moratoriumMonthsMax: 6,
    repaymentYears: 5,
    eligibleCategories: ["SC", "ST", "OBC", "General"],
    genderCriteria: "any",
    collateralRequired: false,
    channelRoute: "PSBs / RRBs / NBFC-MFIs",
    requiredDocuments: [
      "Aadhaar & PAN Card",
      "Udyam Registration Certificate",
      "Past 6 months bank statement",
      "Machinery/Equipment supplier quotation",
      "Business expansion projection",
    ],
    businessTypes: ["micro-enterprise", "trade", "service", "manufacturing", "food processing"],
    officialUrl: "https://mudra.org.in",
    applicationPortal: "https://udyamimitra.in",
    nodal: "Micro Units Development & Refinance Agency (MUDRA)",
    lastVerified: "2026-09-08",
    source: "mudra.org.in official portal",
    partnerTypes: ["PSB", "RRB", "NBFC-MFI"],
    states: "all",
    tags: ["MUDRA", "expansion", "small business"],
    color: "from-teal-500 to-cyan-600",
    icon: "📈",
    status: "active",
  },
  {
    id: "stand-up-india",
    name: "Stand-Up India Scheme",
    shortName: "Stand-Up India",
    shortCode: "SUI",
    description: "Bank loans between ₹10 Lakh and ₹1 Crore for Scheduled Caste (SC), Scheduled Tribe (ST), or Women borrowers to set up greenfield enterprises in manufacturing, services, agri-allied, or trading sectors.",
    purpose: ["business_start", "machinery", "business_expansion"],
    category: ["term_loan", "medium"],
    ministry: "Ministry of Finance",
    implementingBody: "SIDBI / Scheduled Commercial Banks",
    governmentLevel: "central",
    minAge: 18,
    maxAge: 65,
    incomeLimitLakh: 25.0,
    minLoanLakh: 10.0,
    maxLoanLakh: 100.0,
    financingPercent: 85,
    interestRatePercent: 8.5,
    moratoriumMonthsMin: 18,
    moratoriumMonthsMax: 18,
    repaymentYears: 7,
    eligibleCategories: ["SC", "ST"],
    genderCriteria: "any",
    collateralRequired: true,
    channelRoute: "PSBs / Private Scheduled Commercial Banks",
    requiredDocuments: [
      "Caste Certificate (SC/ST)",
      "Aadhaar Card & PAN Card",
      "Comprehensive Detailed Project Report (DPR)",
      "Proof of 15% promoter margin money contribution",
      "Business registration / Udyam Certificate",
      "Collateral or CGSSI guarantee documents",
    ],
    businessTypes: ["manufacturing", "service", "trading", "greenfield enterprise"],
    officialUrl: "https://www.standupmitra.in",
    applicationPortal: "https://www.standupmitra.in",
    nodal: "SIDBI — Stand-Up India",
    lastVerified: "2026-09-08",
    source: "standupmitra.in official portal",
    partnerTypes: ["PSB", "RRB"],
    states: "all",
    tags: ["stand-up india", "SC", "ST", "greenfield", "large loan"],
    color: "from-violet-500 to-indigo-600",
    icon: "🏢",
    status: "active",
  },
  {
    id: "nsfdc-term-loan-legacy",
    scheme_id: "nsfdc-term-loan-legacy",
    name: "Term Loan (LEGACY — DISCONTINUED)",
    shortName: "Term Loan (Legacy)",
    shortCode: "TL-LEGACY",
    short_code: "TL-LEGACY",
    implementingBody: "NSFDC",
    implementing_body: "NSFDC",
    governmentLevel: "central",
    government_level: "central",
    category: ["term_loan"],
    description: "Discontinued effective 01.10.2023. Replaced by Suvidha Loan Scheme (projects up to Rs.10 lakh) and Utkarsh Loan Scheme (projects above Rs.10 lakh up to Rs.50 lakh). Kept in dataset only to prevent stale references — DO NOT surface in active matching.",
    purpose: ["business_start"],
    minAge: 18,
    maxAge: 55,
    incomeLimitLakh: 3.0,
    minLoanLakh: 0.5,
    maxLoanLakh: 15.0,
    financingPercent: 90,
    interestRatePercent: 5.0,
    moratoriumMonthsMin: 3,
    moratoriumMonthsMax: 12,
    repaymentYears: 10,
    eligibleCategories: ["SC"],
    genderCriteria: "any",
    gender_criteria: "any",
    channelRoute: "SCAs / PSBs / RRBs",
    channel_route: "SCAs / PSBs / RRBs",
    requiredDocuments: [],
    businessTypes: [],
    officialUrl: "https://nsfdc.nic.in/en/term-loan",
    official_url: "https://nsfdc.nic.in/en/term-loan",
    nodal: "NSFDC (Historical)",
    lastVerified: "2026-09-08",
    last_verified: "2026-09-08",
    source: "NSFDC Official Notification 01.10.2023",
    sourceUrl: "https://nsfdc.nic.in/en/term-loan",
    source_url: "https://nsfdc.nic.in/en/term-loan",
    partnerTypes: ["SCA"],
    states: "all",
    tags: ["legacy", "discontinued"],
    color: "from-gray-500 to-slate-600",
    icon: "📦",
    status: "discontinued",
    notes: "Discontinued effective 01.10.2023. Replaced by Suvidha Loan Scheme (projects up to Rs.10 lakh) and Utkarsh Loan Scheme (projects above Rs.10 lakh up to Rs.50 lakh). Kept in dataset only to prevent stale references — DO NOT surface in active matching."
  }
];

export const getActiveSchemes = () => SCHEMES.filter(s => s.status === "active");

export const getSchemeById = (id: string) => SCHEMES.find((s) => s.id === id);

export const getSchemesByPurpose = (purpose: SchemePurpose) =>
  getActiveSchemes().filter((s) => s.purpose.includes(purpose));

export const formatLakh = (lakh: number) => {
  if (lakh >= 100) return `₹${(lakh / 100).toFixed(1)} Cr`;
  return `₹${lakh} Lakh`;
};
